name: privai
description: Flutter app with Gemma AI model

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_gemma: ^0.11.13
  whisper_ggml: ^1.7.0
  path_provider: ^2.1.1
  audioplayers: ^5.2.1
  record: ^6.0.0
  kokoro_tts_flutter: ^0.2.1-exp
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_web_auth_2: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/kokoro.onnx
    - assets/voices.json
    - assets/lexicon.json
    - assets/tokenizer_vocab.json
    - assets/us_gold.json
    - assets/us_silver.json
    - assets/models_list.json
